apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  namespace: playground_microservices
  labels:
    app: auth-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: microstore/auth-service:latest
        imagePullPolicy: Never # For local development
        ports:
        - containerPort: 8081
          name: grpc
        env:
        - name: PORT
          value: "8081"
        - name: DATABASE_URL
          value: "postgres://postgres:password@postgres:5432/auth_db?sslmode=disable"
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auth-secrets
              key: jwt-secret
        - name: JWT_EXPIRATION_HOURS
          value: "24"
        - name: REFRESH_TOKEN_EXP_DAYS
          value: "30"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "nc -z localhost 8081"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "nc -z localhost 8081"
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Secret
metadata:
  name: auth-secrets
  namespace: playground_microservices
type: Opaque
data:
  jwt-secret: eW91ci1zdXBlci1zZWNyZXQtand0LWtleS1jaGFuZ2UtaW4tcHJvZHVjdGlvbg== # base64 encoded