apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-service
  namespace: playground_microservices
  labels:
    app: client-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: client-service
  template:
    metadata:
      labels:
        app: client-service
    spec:
      containers:
      - name: client-service
        image: microstore/client-service:latest
        imagePullPolicy: Never # For local development
        ports:
        - containerPort: 8083
          name: http
        env:
        - name: PORT
          value: "8083"
        - name: API_GATEWAY_URL
          value: "http://api-gateway:8080"
        - name: SESSION_SECRET
          valueFrom:
            secretKeyRef:
              name: client-secrets
              key: session-secret
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 8083
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8083
          initialDelaySeconds: 5
          periodSeconds: 5

---
apiVersion: v1
kind: Secret
metadata:
  name: client-secrets
  namespace: playground_microservices
type: Opaque
data:
  session-secret: eW91ci1zdXBlci1zZWNyZXQtc2Vzc2lvbi1rZXktY2hhbmdlLWluLXByb2R1Y3Rpb24= # base64 encoded