apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service
  namespace: playground_microservices
  labels:
    app: product-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service
        image: microstore/product-service:latest
        imagePullPolicy: Never # For local development
        ports:
        - containerPort: 8082
          name: grpc
        env:
        - name: PORT
          value: "8082"
        - name: DATABASE_URL
          value: "postgres://postgres:password@postgres:5432/product_db?sslmode=disable"
        - name: AUTH_SERVICE
          value: "auth-service:8081"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "nc -z localhost 8082"
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - "nc -z localhost 8082"
          initialDelaySeconds: 5
          periodSeconds: 5