apiVersion: v1
kind: Service
metadata:
  name: auth-service
  namespace: playground_microservices
  labels:
    app: auth-service
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
    protocol: TCP
    name: grpc
  selector:
    app: auth-service