apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: playground_microservices
  labels:
    app: client-service
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8083
    protocol: TCP
    name: http
  selector:
    app: client-service